# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mafiahandler.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12mafiahandler.proto\"G\n\x0b\x41\x63tionQuery\x12\x0e\n\x06typeId\x18\x01 \x01(\x03\x12\x10\n\x08targetId\x18\x02 \x01(\x03\x12\x16\n\x0euniqueClientId\x18\x03 \x01(\x03\":\n\x0e\x41\x63tionResponse\x12\x16\n\x0euniqueClientId\x18\x01 \x01(\x03\x12\x10\n\x08resultId\x18\x02 \x01(\x03\"(\n\x08RegQuery\x12\x0e\n\x06typeId\x18\x01 \x01(\x03\x12\x0c\n\x04Name\x18\x02 \x01(\t\"%\n\x0bRegResponse\x12\x16\n\x0euniqueClientId\x18\x01 \x01(\x03\"$\n\nUnRegQuery\x12\x16\n\x0euniqueClientId\x18\x01 \x01(\x03\"!\n\rUnRegResponse\x12\x10\n\x08resultId\x18\x01 \x01(\x03\"%\n\x0bStatusQuery\x12\x16\n\x0euniqueClientId\x18\x01 \x01(\x03\"7\n\x0eStatusResponse\x12\r\n\x05State\x18\x01 \x01(\t\x12\x16\n\x0euniqueClientId\x18\x02 \x01(\x03\"&\n\x0c\x43hatGetQueue\x12\x16\n\x0euniqueClientId\x18\x01 \x01(\x03\"5\n\x11\x43hatQueueResponse\x12\x10\n\x08resultId\x18\x01 \x01(\x03\x12\x0e\n\x06Queues\x18\x02 \x01(\t\"C\n\x0b\x43hatMessage\x12\x16\n\x0euniqueClientId\x18\x01 \x01(\x03\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\x03\x12\x0b\n\x03Msg\x18\x03 \x01(\t\" \n\x0c\x43hatResponse\x12\x10\n\x08resultId\x18\x01 \x01(\x03\x32\x91\x02\n\x0c\x45ngineServer\x12%\n\x08Register\x12\t.RegQuery\x1a\x0c.RegResponse\"\x00\x12+\n\nUnRegister\x12\x0b.UnRegQuery\x1a\x0e.UnRegResponse\"\x00\x12)\n\x06Update\x12\x0c.StatusQuery\x1a\x0f.StatusResponse\"\x00\x12)\n\x06\x41\x63tion\x12\x0c.ActionQuery\x1a\x0f.ActionResponse\"\x00\x12\x30\n\tChatQueue\x12\r.ChatGetQueue\x1a\x12.ChatQueueResponse\"\x00\x12%\n\x04\x43hat\x12\x0c.ChatMessage\x1a\r.ChatResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mafiahandler_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIONQUERY._serialized_start=22
  _ACTIONQUERY._serialized_end=93
  _ACTIONRESPONSE._serialized_start=95
  _ACTIONRESPONSE._serialized_end=153
  _REGQUERY._serialized_start=155
  _REGQUERY._serialized_end=195
  _REGRESPONSE._serialized_start=197
  _REGRESPONSE._serialized_end=234
  _UNREGQUERY._serialized_start=236
  _UNREGQUERY._serialized_end=272
  _UNREGRESPONSE._serialized_start=274
  _UNREGRESPONSE._serialized_end=307
  _STATUSQUERY._serialized_start=309
  _STATUSQUERY._serialized_end=346
  _STATUSRESPONSE._serialized_start=348
  _STATUSRESPONSE._serialized_end=403
  _CHATGETQUEUE._serialized_start=405
  _CHATGETQUEUE._serialized_end=443
  _CHATQUEUERESPONSE._serialized_start=445
  _CHATQUEUERESPONSE._serialized_end=498
  _CHATMESSAGE._serialized_start=500
  _CHATMESSAGE._serialized_end=567
  _CHATRESPONSE._serialized_start=569
  _CHATRESPONSE._serialized_end=601
  _ENGINESERVER._serialized_start=604
  _ENGINESERVER._serialized_end=877
# @@protoc_insertion_point(module_scope)
